### ISSUE TITLE
Content Mappings

### ISSUE THREAD

**Issue by loganfranken** [ucsb-wsg/web-accessibility#8]
If we decide to move forward with removing this section altogether (see #7), we should make sure that all of the content is reflected somewhere in the web guide.

I wanted to create an issue to keep track of all of the mappings:
#### [1. Provide text equivalents to all non-text elements](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#1-provide-text-equivalents-to-all-non-text-elements)

http://webguide.ucsb.edu/html/#images
#### [2. Do not rely on color alone to convey information.](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#2-do-not-rely-on-color-alone-to-convey-information)

https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/106
#### [3. Use markup and style sheets and do so properly. Pages must transform gracefully](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#3-use-markup-and-style-sheets-and-do-so-properly-pages-must-transform-gracefully)

http://webguide.ucsb.edu/css/ (Foreword)
#### [4. Create tables that transform gracefully](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#4-create-tables-that-transform-gracefully)

https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/110
#### [5. Ensure that your web page can be viewed by people with color blindness.](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#5-ensure-that-your-web-page-can-be-viewed-by-people-with-color-blindness)

https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/125
#### [6. Repeat image map links as text somewhere else on the page.](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#6-repeat-image-map-links-as-text-somewhere-else-on-the-page)

Image maps should be used extremely rarely, if at all. This recommendation should just be dropped entirely.
#### [7. Design for device-independence.](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#7-design-for-device-independence)

https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/126
#### [8. Ensure user control of time-sensitive content changes.](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#8-ensure-user-control-of-time-sensitive-content-changes)

https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/127

The recommendations for the `blink` and `marquee` tags can be dropped altogether.
#### [9. Provide mechanisms to help users find content, orient themselves within it, and navigate through it.](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#9-provide-mechanisms-to-help-users-find-content-orient-themselves-within-it-and-navigate-through-it)

https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/128

ASCII art/calendar recommendations can be dropped

http://webguide.ucsb.edu/html/#links
#### [10. Use interim solutions.](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#10-use-interim-solutions)

https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/129

The "non-link item" recommendation can be dropped altogether; semantic markup should be used instead of decorative glyphs
#### [11. Use W3C technologies and guidelines.](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#11-use-w3c-technologies-and-guidelines)

https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/130
#### [12. Ensure that documents are clear and simple.](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#12-ensure-that-documents-are-clear-and-simple)

https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/131
#### [13. Clarify natural language usage](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#13-clarify-natural-language-usage)

http://webguide.ucsb.edu/header/
#### [14. Provide links to plug-ins and applets](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#14-provide-links-to-plug-ins-and-applets)

https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/132
#### [15. Use accessible Flash files:](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#15-use-accessible-flash-files)

(Covered below)
#### [16. Use accessible PDF files:](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#16-use-accessible-pdf-files)

(Covered below)
#### [17. Use accessible multimedia files:](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#17-use-accessible-multimedia-files)

(Covered below)
### [Guideline: Decrease maintenance and increase consistency](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#guideline-decrease-maintenance-and-increase-consistency)

http://webguide.ucsb.edu/css/
### [Guideline: User override of styles](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#guideline-user-override-of-styles)

http://webguide.ucsb.edu/css/
https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/114
### [Guideline: Units of measure](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md)

https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/119
### [Guideline: Generated content](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#guideline-generated-content)

https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/122
### [Guideline: Fonts](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#guideline-fonts)

This recommendation can be removed altogether: `big` is now completely deprecated and `small` has a defined semantic purpose (http://html5doctor.com/small-hr-element/).

The general notion that styling should be handled by CSS is already covered: http://webguide.ucsb.edu/css/
### [Guideline: Text style effects](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#guideline-text-style-effects)

https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/127
### [Guideline: Text instead of images](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#guideline-text-instead-of-images)

http://webguide.ucsb.edu/html/
https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/123
### [Guideline: Text formatting and position](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#guideline-text-formatting-and-position)

http://webguide.ucsb.edu/css/
### [Guideline: Colors](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#guideline-colors)

http://webguide.ucsb.edu/css/
https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/124
### [Guideline: Providing contextual clues in HTML lists](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#guideline-providing-contextual-clues-in-html-lists)

No need to transfer this rule as it's self-evident
### [Guideline: Layout, positioning, layering, and alignment](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#guideline-layout-positioning-layering-and-alignment)

http://webguide.ucsb.edu/css/
http://webguide.ucsb.edu/html/
### [Guideline: Rules and borders](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#guideline-rules-and-borders)

http://webguide.ucsb.edu/css/
### [Guideline: Using style sheet positioning and markup to transform gracefully](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#guideline-using-style-sheet-positioning-and-markup-to-transform-gracefully)

http://webguide.ucsb.edu/css/
### [Guideline: Creating movement with style sheets and scripts](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#guideline-creating-movement-with-style-sheets-and-scripts)

https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/127
### [Guideline: Aural Cascading Style Sheets](https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#guideline-aural-cascading-style-sheets)

https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/133
## Resources

https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/134
## Appendix I: Links to Relevant Case Law

https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/135
## Appendix II: The Agencies Who Enforce Access

https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/135
## Appendix III: Software

https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/136
## Appendix IV: Designing Accessible Flash PAGES

No need to migrate this; we shouldn't be encouraging the use of Flash at all
## Appendix V: Designing Accessible PDF Documents

https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/137
## Appendix VI: Designing Accessible Multimedia Files

https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/138
## Appendix VII: Tools for Validating Accessibility of Web Pages

https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/136

**Comment by UCSB-jcolo** [comment]
Cool.
Thanks Logan!

**Comment by loganfranken** [comment]
Alright: finally finished completing all the mappings between the web accessibility guide content and either (1) existing content in the web guide or (2) issues discussing the future creation of that content.

Closing this now since this ticket was primarily concerned with discovering and documenting those mappings.

**Comment by garster** [comment]
:shipit:
